greeting.message: Hello world from spring boot config server
app:
   name: Micro Service Config
   desc: Ways to handle ${application.name}
my.list.values: Male, Female, Non

db:
   connection: connection string from sonfig server
   host: 129.0.0.1
   port: 1501
